package io.github.marcofanti.aauth.personserver.persistence;

import com.zaxxer.hikari.HikariDataSource;
import java.net.URI;
import javax.sql.DataSource;

/**
 * Translate the Python server's SQLAlchemy-style {@code AAUTH_DATABASE_URL} values into JDBC
 * data sources: {@code sqlite:///rel.db} / {@code sqlite:////abs.db} and
 * {@code postgresql+psycopg://user:pass@host:port/db}.
 */
public final class DatabaseUrls {

    private DatabaseUrls() {}

    public static DataSource dataSourceFor(String sqlalchemyUrl) {
        HikariDataSource dataSource = new HikariDataSource();
        if (sqlalchemyUrl.startsWith("sqlite:")) {
            String path = sqlalchemyUrl.substring("sqlite:".length());
            while (path.startsWith("//") && !path.startsWith("///")) {
                path = path.substring(1);
            }
            // sqlite:///rel → rel, sqlite:////abs → /abs (SQLAlchemy slash rules).
            if (path.startsWith("///")) {
                path = path.substring(3);
            }
            dataSource.setJdbcUrl("jdbc:sqlite:" + path);
            // SQLite: single connection avoids writer lock contention.
            dataSource.setMaximumPoolSize(1);
            return dataSource;
        }
        if (sqlalchemyUrl.startsWith("postgresql")) {
            URI uri = URI.create(sqlalchemyUrl.replaceFirst("^postgresql(\\+\\w+)?", "postgresql"));
            StringBuilder jdbc = new StringBuilder("jdbc:postgresql://").append(uri.getHost());
            if (uri.getPort() != -1) {
                jdbc.append(':').append(uri.getPort());
            }
            jdbc.append(uri.getPath());
            dataSource.setJdbcUrl(jdbc.toString());
            if (uri.getUserInfo() != null) {
                String[] parts = uri.getUserInfo().split(":", 2);
                dataSource.setUsername(parts[0]);
                if (parts.length > 1) {
                    dataSource.setPassword(parts[1]);
                }
            }
            return dataSource;
        }
        throw new IllegalArgumentException("Unsupported AAUTH_DATABASE_URL: " + sqlalchemyUrl);
    }

    /** {@code Base.metadata.create_all} equivalent — idempotent DDL for both dialects. */
    public static void initDb(DataSource dataSource) {
        String[] ddl = {
            "CREATE TABLE IF NOT EXISTS ps_mission (s256 TEXT PRIMARY KEY, blob_b64 TEXT NOT NULL, "
                    + "state TEXT NOT NULL, agent_id TEXT NOT NULL, approved_at TEXT NOT NULL, "
                    + "owner_id TEXT, approver TEXT NOT NULL, description TEXT NOT NULL, "
                    + "approved_tools_json TEXT, capabilities_json TEXT)",
            "CREATE TABLE IF NOT EXISTS ps_mission_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "s256 TEXT NOT NULL, ts TEXT NOT NULL, kind TEXT NOT NULL, payload_json TEXT NOT NULL)",
            "CREATE TABLE IF NOT EXISTS ps_pending (pending_id TEXT PRIMARY KEY, interaction_code TEXT NOT NULL, "
                    + "code_unusable BOOLEAN NOT NULL DEFAULT FALSE, is_open BOOLEAN NOT NULL DEFAULT TRUE, "
                    + "owner_id TEXT, requirement TEXT, record_json TEXT NOT NULL)",
            "CREATE TABLE IF NOT EXISTS ps_trusted_agent_server (issuer TEXT PRIMARY KEY, display_name TEXT, "
                    + "jwks_uri TEXT NOT NULL, jwks_fingerprint TEXT NOT NULL, added_at TEXT)",
            "CREATE TABLE IF NOT EXISTS ps_issued_token (issued_id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, "
                    + "owner_id TEXT, resource_iss TEXT, resource_scope TEXT, justification TEXT, "
                    + "issue_method TEXT NOT NULL, token_jti TEXT, issued_at TEXT NOT NULL, expires_at TEXT)",
            "CREATE TABLE IF NOT EXISTS as_pending_registration (id TEXT PRIMARY KEY, stable_pub_json TEXT NOT NULL, "
                    + "ephemeral_pub_json TEXT NOT NULL, agent_name TEXT NOT NULL, stable_jkt TEXT NOT NULL, "
                    + "created_at TEXT NOT NULL, expires_at TEXT NOT NULL, status TEXT NOT NULL)",
            "CREATE TABLE IF NOT EXISTS as_binding (agent_id TEXT PRIMARY KEY, agent_name TEXT NOT NULL, "
                    + "created_at TEXT NOT NULL, revoked BOOLEAN NOT NULL DEFAULT FALSE)",
            "CREATE TABLE IF NOT EXISTS as_binding_jkt (jkt TEXT PRIMARY KEY, agent_id TEXT NOT NULL, "
                    + "position BIGINT NOT NULL DEFAULT 0)",
        };
        try (var connection = dataSource.getConnection();
                var statement = connection.createStatement()) {
            for (String sql : ddl) {
                // SQLite has no IDENTITY syntax; fall back to its implicit rowid autoincrement.
                if (connection
                        .getMetaData()
                        .getDatabaseProductName()
                        .toLowerCase(java.util.Locale.ROOT)
                        .contains("sqlite")) {
                    sql = sql.replace(
                            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT");
                }
                statement.execute(sql);
            }
        } catch (java.sql.SQLException e) {
            throw new IllegalStateException("failed to initialize database schema: " + e.getMessage(), e);
        }
    }
}
